name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: raghudevopsb78/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend
      npm_install: false
    secrets: inherit
